### ISSUE TITLE
No module named more_itertools

### ISSUE THREAD

**Issue by chanshing** [TentativeConvert/Syndicator#1]
When running `main.py` I get the error `no module named more_itertools`. I simply removed that import and it seems to be working fine so far.

**Comment by TentativeConvert** [comment]
Thanks for reporting this!  I don't remember why I wanted to import this module, and I agree that it seems superfluous to do so, so I've removed it (see commit 964db60f4b8cb286f2c75a30f0dfa6a11b6ed5fe).
