### ISSUE TITLE
How do you detect Unison's state?

### ISSUE THREAD

**Issue by villasenor** [TentativeConvert/Syndicator#2]
Thinking of adapting this for other platforms and use cases - you did a great job here! Question though...at a quick glance, I'm not seeing how you detect Unison's state. Could you point me in the right direction? I'd like to be able to get status updates from Unison when it is syncing, idle, etc.

Thanks!

**Comment by TentativeConvert** [comment]
I detect Unison's status be listening to the command line output.  The line of code you're looking for is:
https://github.com/TentativeConvert/Syndicator/blob/d1accbbd34427e71f9826aaaaf5169fcfb9e6646/ExternalProcess.py#L33

However, if you're after a more flexible tool, I suggest you have a look at Bjarni Runar's [gui-o-matic](https://github.com/mailpile/gui-o-matic).  I wouldn't have written Syndicator if gui-o-matic had existed at the time and if I had been aware of it.

Sorry for the late reply, by the way – I forgot to subscribe to email notifications, and only saw your question by chance this morning.

**Comment by villasenor** [comment]
No worries about the delay - thanks for the reply! :+1:
