### ISSUE TITLE
Fatal error: Filesystem watcher error: cannot add a watcher: system limit reached

### ISSUE THREAD

**Issue by thd-fox** [TentativeConvert/Syndicator#5]
The error is clear I think.

Where can I increase the file limit?
I found this similar issue here:
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

How can I fix this issue with your watcher?

**Comment by TentativeConvert** [comment]
Doesn't the very link that you included tell you how to fix the issue?  In any case, please note that this is not "my watcher".  The watcher `unsion-fsmonitor` is part of `unsion`, and any issues should be reported here:

https://github.com/bcpierce00/unison/issues
